#!/bin/bash

# Update package list
apt-get update

# Install python-pip
apt-get install -y python-pip

# Install nose, behave, coverage, pexpect, selenium
pip install -r requirements.txt

# Install PhantomJS
apt-get install -y phantomjs

# Clean up downloaded archives
apt-get clean
