#!/bin/bash

# Install python-pip 1.5.4-1. Latest version of pip installation broken; hence installing older!
sudo apt-get install -y python-pip=1.5.4-1

# Install nose
sudo pip install nose

# Install coverage
sudo pip install coverage
